services:
  proxmox-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxmox-mcp
    restart: unless-stopped
    init: true
    tty: true
    stdin_open: true
    stop_signal: SIGINT
    environment:
      PROXMOX_MCP_CONFIG: /app/proxmox-config/config.json
      PYTHONPATH: /app/src
    working_dir: /app
    volumes:
      - ./proxmox-config:/app/proxmox-config:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "/app/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
