labels: ["discussion", "general"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for starting a discussion! This is the place for open-ended conversations about ProxmoxMCP.

        Before posting, please check:
        - [ ] [Existing discussions](https://github.com/basher83/ProxmoxMCP/discussions) for similar topics
        - [ ] [README documentation](https://github.com/basher83/ProxmoxMCP#readme) for basic information
        - [ ] [Issues](https://github.com/basher83/ProxmoxMCP/issues) if this is a bug report or feature request

  - type: input
    attributes:
      label: "Discussion Topic"
      description: "What would you like to discuss?"
      placeholder: "e.g., Best practices for ProxmoxMCP in production environments"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Description"
      description: "Provide more details about what you'd like to discuss"
      placeholder: "Share your thoughts, experiences, or questions..."
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Discussion Category"
      description: "What category best fits this discussion?"
      options:
        - General
        - Best Practices
        - Use Cases
        - Integration
        - Performance
        - Security
        - Feature Ideas
        - Troubleshooting Help
        - Community
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Your Experience"
      description: "Tell us about your experience with ProxmoxMCP (optional)"
      placeholder: "e.g., New user, been using for 6 months, production deployment..."

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Any additional information that might be helpful"
      placeholder: "Environment details, related tools, specific goals..."
