name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install UV package manager
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      # Install dependencies
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      # Run black formatter
      - name: Run black
        run: |
          source .venv/bin/activate
          black . --check --diff || black .

      # Run ruff with auto-fix
      - name: Run ruff
        run: |
          source .venv/bin/activate
          ruff check . --fix --exit-zero

      # Run mypy for type checking (informational only)
      - name: Run mypy
        run: |
          source .venv/bin/activate
          mypy . || true

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef